### ISSUE TITLE
FileBrowser and ReplicatorRequest example failing

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/examples#1]
```
c$ corto run FileBrowser/
object '<0x7fcfda702a00>' is not of type '/corto/ast/Object'
    type = /corto/ast/UnresolvedReference

rm: include/FileBrowser__type.h: No such file or directory
rake aborted!
Command failed with status (1): [rm include/FileBrowser__type.h...]
/usr/local/lib/corto/0.2/build/package.rb:68:in `rescue in block in <top (required)>'
/usr/local/lib/corto/0.2/build/package.rb:64:in `block in <top (required)>'
/Users/JohnnyLee/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/JohnnyLee/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Command failed with status (): [corto pp  FileBrowser.cx --scope FileBrows...]
/usr/local/lib/corto/0.2/build/package.rb:65:in `block in <top (required)>'
/Users/JohnnyLee/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/JohnnyLee/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => include/FileBrowser__type.h
(See full trace by running task with --trace)
corto: build: rake failed (returncode 1)
c$ which corto
/usr/local/bin/corto
c$ corto --version
corto version 0.2.8-alpha (x64-darwin) build Nov 30 2015 15:51:39

c$ corto
corto shell - type 'help' for instructions.
/ $ ast  
name:         ast
parent:       corto
owner:        <this>
state:        V|DCL|DEF
attributes:   S|P
type:         corto/lang/package
value:        {url="http://corto.io/doc/corto/ast"}

/ $ ast/Object  
name:         Object
parent:       corto/ast
owner:        <this>
state:        V|DCL|DEF
attributes:   S|P
type:         corto/lang/class
value:        {kind=COMPOSITE reference=true parentType=null parentState=DECLARED|DEFINED defaultType=null defaultProcedureType=null kind=CLASS base=/corto/ast/Storage baseAccess=READONLY implements={}}
initializer:     {value=null}
```

**Comment by SanderMertens** [comment]
This was solved with `0.2.9`
